# Desplegar.yml    (GITHUB)

name: Despliegue

on: [push]
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    #paso:  Enviar repositorio a GitHUb
    - uses: actions/checkout@master   
    #paso: envio fuentes a ubuntu por scp
    - name: Copiar archivos con scp
      run: |
        scp -${{ secrets.SSHKEY }} node/database/* ${{ secrets.USERNAME }}@s${{ secrets.HOST }}:/home/ubuntu/app